# Generated by Django 3.2.3 on 2021-06-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_galleryimage_image_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image_min',
            new_name='image_cropped',
        ),
    ]
