# Generated by Django 3.2.3 on 2021-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_rename_image_min_galleryimage_image_cropped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveSmallIntegerField()),
                ('need_room_in_kh', models.BooleanField(default=False)),
                ('need_room_in_penates', models.BooleanField(default=False)),
                ('transfer_to', models.BooleanField(default=False)),
                ('transfer_from_first_day', models.BooleanField(default=False)),
                ('transfer_from_second_day', models.BooleanField(default=False)),
            ],
        ),
    ]
